In [16]:
library(dplyr)
library(tidyverse)

dat = read.csv("owid-covid-data .csv")
dat$id = 1:nrow(dat)

cat("Latest date available:",max(dat$date)) #latest date available.
#Use a slightly earlier date so it's more likely data will be available for more countries.
date_ = "2021-09-03"

latest = filter(dat, dat$date == date_)

#Data frame of only 'total tests' data.
tests = data.frame(id = latest$id,total_tests = latest$total_tests)

#Remove missing values.
tests = na.omit(tests)

#How many countries have 'total tests' data for the chosen date.
cat("# of countries with total_tests data:",nrow(tests))
tests = left_join(tests,latest,by="id")
tests_df = data.frame(country=tests$location,total_tests=tests$total_tests.x,tests_per_1000=tests$total_tests_per_thousand)
head(tests_df)

Latest date available: 2021-10-03# of countries with total_tests data: 85

  country    total_tests tests_per_1000
1 Argentina  13491660     295.832
2 Armenia     1560430     525.729
3 Austria    77475962    8567.438
4 Azerbaijan  4535906     443.681
5 Bahrain     6004130    3434.277
6 Belarus     7859365     832.307

Or could just get the latest date available for every country:

In [19]:
dat$id = 1:nrow(dat)
test = data.frame(id = dat$id,tests = dat$total_tests)
test = na.omit(test)

test = left_join(test,dat,by="id")

latest = test %>%
  group_by(location) %>%
  summarize(date=max(date))

total_tests = left_join(latest,test,by=c("location","date")) %>%
  select(location,tests,total_tests_per_thousand,date) %>%
  as.data.frame()

total_tests

    location               tests     total_tests_per_thousand date
1   Albania                   737014  256.537                 2021-06-13
2   Andorra                   214094 2767.717                 2021-09-26
3   Antigua and Barbuda        16700  169.152                 2021-07-13
4   Argentina               14046650  308.001                 2021-09-24
5   Armenia                  1712685  577.025                 2021-09-30
6   Australia               37631431 1459.249                 2021-09-29
7   Austria                 86750951 9593.084                 2021-09-29
8   Azerbaijan               4839863  473.413                 2021-09-29
9   Bahamas                   145042  365.424                 2021-09-26
10  Bahrain                  6427427 3676.397                 2021-09-29
11  Bangladesh               9707922   58.375                 2021-09-30
12  Belarus                  8414751  891.122                 2021-09-27
13  Belgium                 19989310 1718.426                 2021-09-28
14  Belize                    259340  640.480                 2021-09-28
15  Benin                     640586   51.448                 2021-05-19
16  Bhutan                   1150014 1474.566                 2021-09-30
17  Bolivia                  2438941  206.115                 2021-09-29
18  Bosnia and Herzegovina   1227043  375.995                 2021-09-30
19  Botswana                 1728392  720.992                 2021-09-17
20  Brazil                  31716527  148.213                 2021-05-24
21  Bulgaria                 4786244  693.995                 2021-09-29
22  Cambodia                 2289480  135.101                 2021-09-10
23  Canada                  43215201 1135.213                 2021-09-29
24  Chile                   21500852 1119.115                 2021-09-29
25  China                  160000000  110.787                 2020-08-06
26  Colombia                25393612  495.332                 2021-09-28
27  Costa Rica               1879112  365.653                 2021-09-26
28  Cote d'Ivoire            1011465   37.387                 2021-09-29
29  Croatia                  2823030  691.638                 2021-09-30
30  Cuba                     5296762  468.015                 2021-07-04
... ...                    ...       ...                      ...
101 Rwanda                   2806919  211.420                 2021-09-30
102 Saint Kitts and Nevis      41035  766.350                 2021-09-30
103 Saudi Arabia            28902511  817.826                 2021-09-29
104 Senegal                   809390   47.068                 2021-09-29
105 Serbia                   5650408  830.381                 2021-09-30
106 Singapore               19560496 3317.203                 2021-09-27
107 Slovakia                41912482 7675.258                 2021-09-29
108 Slovenia                 1579004  759.603                 2021-09-29
109 South Africa            17588025  292.929                 2021-09-27
110 South Korea             13394600  261.077                 2021-09-30
111 South Sudan               164472   14.451                 2021-05-26
112 Spain                   57549938 1231.141                 2021-09-16
113 Sri Lanka                5281658  245.689                 2021-09-30
114 Switzerland             10396629 1192.890                 2021-09-29
115 Taiwan                   3393177  142.242                 2021-09-29
116 Thailand                13258565  189.541                 2021-09-18
117 Timor                     194367  144.632                 2021-09-10
118 Togo                      509788   60.129                 2021-09-27
119 Trinidad and Tobago       344713  245.632                 2021-09-26
120 Tunisia                  2920578  244.691                 2021-09-29
121 Turkey                  86269464 1014.425                 2021-09-30
122 Uganda                   1675142   35.548                 2021-09-25
123 Ukraine                 12829867  295.165                 2021-09-30
124 United Arab Emirates    83975380 8405.033                 2021-09-30
125 United Kingdom         273286284 4006.712                 2021-09-29
126 United States          574986405 1727.126                 2021-09-27
127 Uruguay                  3575666 1025.971                 2021-09-29
128 Vietnam                 20041268  204.151                 2021-09-22
129 Zambia                   2437088  128.806                 2021-09-27
130 Zimbabwe                 1247592   82.665                 2021-09-26